<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageType>Template</PackageType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Company.CategoryOrProject.ProjectName</PackageId>
    <Title>Aws lambda clean architecture project template</Title>
    <Version>1.0.0</Version>
    <Authors>thushxr</Authors>
    <Company>thushxr</Company>
    <Description>Lambda project built using cloud formation applicaition and deployed through aws cloud formation, which follows microservcie and clean architecture</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/thushar-p/aws-cloud-formation-lambda-template</RepositoryUrl>
    <FileVersion>1.0.1</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>aws; cloudformation; dotnet; lambda; microservice;</PackageTags>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
	<PackageReference Include="AWSSDK.SecretsManager" Version="4.0.3.1" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
	<PackageReference Include="MySql.Data" Version="9.2.0" />
	<PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\Dtos\" />
    <Folder Include="Application\Interfaces\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Core\Interfaces\" />
    <Folder Include="Core\Entities\" />
    <Folder Include="Core\Enums\" />
    <Folder Include="Infrastructure\ExternalServices\" />
    <Folder Include="Infrastructure\Repositories\" />
  </ItemGroup>
</Project>